title: Settings
data:
  site_name: 'epiclaravel.dev'
  personality: casual
  show_signup: true
  social:
    -
      name: Twitter
      url: 'https://twitter.com/connor11528'
      icon: site/social-icons/twitter.svg
    -
      name: Github
      url: 'https://github.com/connor11528/epiclaravel.dev'
      icon: site/social-icons/github.svg
    -
      name: Email
      url: 'mailto:connor@employbl.com'
      icon: site/social-icons/email.svg
